# Generated by Django 5.2.1 on 2025-05-22 21:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_patrimonial', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código Patrimonial (Generado por el Sistema)')),
                ('codigo_anterior', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Inventario Anterior')),
                ('descripcion', models.TextField(verbose_name='Descripción del Bien')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('serial', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Serial del Fabricante')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('fecha_adquisicion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Adquisición')),
                ('n_orden_compra_factura', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Orden de Compra o Factura')),
                ('nombre_proveedor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Proveedor')),
                ('valor_unitario_bs', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Valor Unitario en Bs.')),
                ('valor_unitario_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Valor Unitario en $')),
                ('ubicacion_fisica_especifica', models.CharField(max_length=255, verbose_name='Ubicación Física Específica')),
                ('responsable_asignado_nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Responsable Asignado')),
                ('responsable_asignado_cargo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Cargo del Responsable Asignado')),
                ('estado_bien', models.CharField(choices=[('NUEVO', 'Nuevo'), ('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo'), ('EN_REPARACION', 'En Reparación'), ('OBSOLETO', 'Obsoleto'), ('DESINCORPORADO', 'Desincorporado')], default='NUEVO', max_length=20, verbose_name='Estado del Bien')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Bien',
                'verbose_name_plural': 'Bienes',
                'ordering': ['-fecha_creacion', 'descripcion'],
            },
        ),
    ]
