# Generated by Django 5.2.1 on 2025-06-03 05:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0001_initial'),
        ('unidades_administrativas_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('INCORPORACION', 'Incorporación'), ('TRASLADO', 'Traslado'), ('DESINCORPORACION', 'Desincorporación'), ('ACTUALIZACION_ESTADO', 'Actualización de Estado')], max_length=30, verbose_name='Tipo de Movimiento')),
                ('fecha_movimiento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora del Movimiento')),
                ('responsable_anterior_nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Responsable Anterior')),
                ('responsable_nuevo_nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Responsable Nuevo')),
                ('ubicacion_anterior_especifica', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación Física Anterior')),
                ('ubicacion_nueva_especifica', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación Física Nueva')),
                ('motivo_desincorporacion', models.TextField(blank=True, null=True, verbose_name='Motivo de Desincorporación/Movimiento')),
                ('numero_oficio_referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Oficio o Documento de Referencia')),
                ('observaciones_movimiento', models.TextField(blank=True, null=True, verbose_name='Observaciones del Movimiento')),
                ('fecha_creacion_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación del Registro')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='bienes_app.bien', verbose_name='Bien Afectado')),
                ('unidad_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_destino', to='unidades_administrativas_app.unidadadministrativa', verbose_name='Unidad de Destino')),
                ('unidad_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_origen', to='unidades_administrativas_app.unidadadministrativa', verbose_name='Unidad de Origen')),
                ('usuario_registra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registra')),
            ],
            options={
                'verbose_name': 'Movimiento de Bien',
                'verbose_name_plural': 'Movimientos de Bienes',
                'ordering': ['-fecha_movimiento', '-fecha_creacion_registro'],
            },
        ),
    ]
