# Generated by Django 5.2.1 on 2025-06-03 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0002_movimientobien'),
        ('unidades_administrativas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='unidad_administrativa_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bienes_asignados', to='unidades_administrativas_app.unidadadministrativa', verbose_name='Unidad Administrativa Actual'),
        ),
    ]
