# Generated by Django 5.2.1 on 2025-06-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0003_bien_unidad_administrativa_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='metodo_depreciacion',
            field=models.CharField(blank=True, choices=[('LINEA_RECTA', 'Línea Recta'), ('SALDO_DECRECIENTE', 'Saldo Decreciente')], max_length=50, null=True, verbose_name='Método de Depreciación'),
        ),
        migrations.AddField(
            model_name='bien',
            name='valor_residual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Valor Residual o de Salvamento (Bs.)'),
        ),
        migrations.AddField(
            model_name='bien',
            name='vida_util_estimada_anios',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Vida Útil Estimada (Años)'),
        ),
    ]
