# Generated by Django 5.2.1 on 2025-06-14 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0004_bien_metodo_depreciacion_bien_valor_residual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepreciacionMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField(verbose_name='Mes del Cálculo')),
                ('anio', models.PositiveIntegerField(verbose_name='Año del Cálculo')),
                ('valor_depreciado_mes', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Valor Depreciado en el Mes')),
                ('depreciacion_acumulada', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Depreciación Acumulada')),
                ('valor_neto_en_libros', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Valor Neto en Libros')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Cálculo')),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciaciones', to='bienes_app.bien', verbose_name='Bien Depreciado')),
            ],
            options={
                'verbose_name': 'Cálculo de Depreciación',
                'verbose_name_plural': 'Cálculos de Depreciación',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('bien', 'mes', 'anio')},
            },
        ),
    ]
