# Generated by Django 5.2.1 on 2025-06-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0005_depreciacionmensual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='codigo_patrimonial',
            field=models.CharField(default='TEMP', max_length=50, unique=True, verbose_name='Código Patrimonial'),
            preserve_default=False,
        ),
    ]
