# Generated by Django 5.2.1 on 2025-07-04 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0005_depreciacionmensual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría de Bien',
                'verbose_name_plural': 'Categorías de Bienes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='bien',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bienes_app.categoria', verbose_name='Categoría'),
        ),
    ]
