# Generated by Django 5.2.1 on 2025-07-31 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0006_categoria_bien_categoria'),
        ('proveedores_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bien',
            name='nombre_proveedor',
        ),
        migrations.AddField(
            model_name='bien',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores_app.proveedor', verbose_name='Proveedor'),
        ),
    ]
