# Generated by Django 5.2.1 on 2025-07-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bienes_app', '0007_remove_bien_nombre_proveedor_bien_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='motivo_adquisicion',
            field=models.CharField(choices=[('COMPRA_DIRECTA', 'Compra Directa'), ('LICITACION', 'Licitación Pública'), ('DACION_PAGO', 'Dación en Pago'), ('DONACION', 'Donación'), ('TRANSFERENCIA', 'Transferencia de Otros Organismos'), ('CONSTRUCCION_PROPIA', 'Construcción Propia'), ('RECUPERACION', 'Recuperación de Bienes'), ('COMODATO', 'Comodato'), ('ARRENDAMIENTO', 'Arrendamiento con Opción de Compra'), ('HERENCIA', 'Herencia o Legado'), ('OTRO', 'Otro')], default='COMPRA_DIRECTA', max_length=50, verbose_name='Motivo de Adquisición'),
        ),
    ]
