# Generated by Django 5.2.1 on 2025-07-24 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaSeguridadUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_1', models.CharField(max_length=255, verbose_name='Pregunta de Seguridad 1')),
                ('respuesta_1_hash', models.CharField(max_length=128, verbose_name='Respuesta de Seguridad 1 (Hasheada)')),
                ('pregunta_2', models.CharField(max_length=255, verbose_name='Pregunta de Seguridad 2')),
                ('respuesta_2_hash', models.CharField(max_length=128, verbose_name='Respuesta de Seguridad 2 (Hasheada)')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_seguridad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preguntas de Seguridad de Usuario',
                'verbose_name_plural': 'Preguntas de Seguridad de Usuarios',
            },
        ),
    ]
