# Generated by Django 5.2.1 on 2025-05-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=255, unique=True, verbose_name='Nombre del Proveedor')),
                ('rif', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='RIF del Proveedor')),
                ('direccion_fiscal', models.TextField(blank=True, null=True, verbose_name='Dirección Fiscal')),
                ('contacto_principal_nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Contacto Principal')),
                ('contacto_principal_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del Contacto Principal')),
                ('contacto_principal_telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono del Contacto Principal')),
                ('activo', models.BooleanField(default=True, verbose_name='Proveedor Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre_proveedor'],
            },
        ),
    ]
